// SONAR - 수집 소스 / 원문 피드 / 정형화된 리스크 이벤트 시드 (기준일 2026-09-15)

export const riskSources = [
  { sourceId:'SRC01', name:"Lloyd's List Intelligence", sourceType:'NEWS',    url:'https://lloydslist.com/rss',           language:'en', trustWeight:0.95, collectIntervalMin:30,  enabled:true,  lastCollectedAt:'2026-09-15T03:30:00Z' },
  { sourceId:'SRC02', name:'Reuters Maritime',          sourceType:'NEWS',    url:'https://reuters.com/markets/shipping', language:'en', trustWeight:0.92, collectIntervalMin:15,  enabled:true,  lastCollectedAt:'2026-09-15T04:00:00Z' },
  { sourceId:'SRC03', name:'UKMTO 항행경보',            sourceType:'GOV',     url:'https://ukmto.org/advisories',        language:'en', trustWeight:0.98, collectIntervalMin:10,  enabled:true,  lastCollectedAt:'2026-09-15T04:05:00Z' },
  { sourceId:'SRC04', name:'IMO / MSC 공지',            sourceType:'GOV',     url:'https://imo.org/circulars',           language:'en', trustWeight:0.96, collectIntervalMin:120, enabled:true,  lastCollectedAt:'2026-09-15T02:00:00Z' },
  { sourceId:'SRC05', name:'선사 고객 공지 (통합)',      sourceType:'NOTICE',  url:'https://sonar.internal/carrier-notice',language:'en', trustWeight:0.90, collectIntervalMin:60,  enabled:true,  lastCollectedAt:'2026-09-15T03:00:00Z' },
  { sourceId:'SRC06', name:'NOAA / 기상청 해상특보',     sourceType:'WEATHER', url:'https://noaa.gov/marine-warnings',    language:'en', trustWeight:0.94, collectIntervalMin:30,  enabled:true,  lastCollectedAt:'2026-09-15T03:45:00Z' },
  { sourceId:'SRC07', name:'TradeWinds',                sourceType:'NEWS',    url:'https://tradewindsnews.com/rss',      language:'en', trustWeight:0.85, collectIntervalMin:60,  enabled:true,  lastCollectedAt:'2026-09-15T03:10:00Z' },
  { sourceId:'SRC08', name:'소셜 채널 (X / 커뮤니티)',   sourceType:'SOCIAL',  url:'https://api.x.com/2/search',          language:'en', trustWeight:0.45, collectIntervalMin:10,  enabled:false, lastCollectedAt:'2026-09-12T10:00:00Z' }
];

export const rawFeeds = [
  { rawFeedId:'RF01', sourceId:'SRC03', externalId:'UKMTO-2026-0912-A',
    title:'ADVISORY 2026/041 - Increased boarding and detention activity, Strait of Hormuz',
    body:'UKMTO has received multiple reports of armed boarding attempts and vessel detentions in the vicinity of the Strait of Hormuz since 08 SEP 2026. Merchant vessels transiting the area are advised to maintain maximum vigilance, report position to UKMTO, and consider delaying transit where commercially viable. Two container vessels were detained on 10 SEP and remain held at Bandar Abbas.',
    url:'https://ukmto.org/advisories/2026-041', publishedAt:'2026-09-12T06:20:00Z', collectedAt:'2026-09-12T06:31:00Z', processStatus:'PROCESSED' },
  { rawFeedId:'RF02', sourceId:'SRC03', externalId:'UKMTO-2026-0901-B',
    title:'ADVISORY 2026/038 - Resumption of attacks on merchant shipping, Bab el-Mandeb',
    body:'Following a three month lull, attacks against merchant shipping have resumed in the southern Red Sea and Bab el-Mandeb strait. Three USV (uncrewed surface vessel) attacks were reported between 01 and 09 SEP 2026. War risk underwriters have reinstated the enhanced premium zone. Vessels are advised to transit at maximum safe speed during hours of darkness or route via the Cape of Good Hope.',
    url:'https://ukmto.org/advisories/2026-038', publishedAt:'2026-09-01T11:00:00Z', collectedAt:'2026-09-01T11:14:00Z', processStatus:'PROCESSED' },
  { rawFeedId:'RF03', sourceId:'SRC06', externalId:'NOAA-TY-NEGURI-08',
    title:'Typhoon NEGURI (2618) - Warning #08, East China Sea',
    body:'Typhoon NEGURI is forecast to track north-northwest and make landfall near the Yangtze estuary between 17 and 19 SEP 2026 with maximum sustained winds of 41 m/s. Shanghai Port Authority has issued a pre-closure notice for Yangshan and Waigaoqiao terminals effective 16 SEP 1800LT. Ningbo-Zhoushan is expected to suspend operations for approximately 48 hours.',
    url:'https://noaa.gov/marine/neguri-08', publishedAt:'2026-09-14T21:00:00Z', collectedAt:'2026-09-14T21:12:00Z', processStatus:'PROCESSED' },
  { rawFeedId:'RF04', sourceId:'SRC01', externalId:'LL-2026-091401',
    title:'Dutch and Belgian dockers announce 72-hour strike over automation deal',
    body:'FNV Havens and ABVV Transcom have jointly served notice of a 72 hour work stoppage at Rotterdam and Antwerp container terminals, planned for 14-17 OCT 2026, after talks on terminal automation collapsed. A further escalation to a rolling one week action has not been ruled out. Terminal operators say contingency plans are in place but berth productivity is expected to fall sharply.',
    url:'https://lloydslist.com/2026/091401', publishedAt:'2026-09-14T09:30:00Z', collectedAt:'2026-09-14T09:41:00Z', processStatus:'PROCESSED' },
  { rawFeedId:'RF05', sourceId:'SRC04', externalId:'ACP-ADV-2026-27',
    title:'Panama Canal Authority - Transit slot reduction advisory No. 27',
    body:'Due to continued below-average precipitation in the Gatun watershed, the Panama Canal Authority will reduce daily booking slots from 32 to 27 effective 01 SEP 2026 until further notice. Maximum authorised draft remains at 13.11 m TFW. Vessels without a confirmed booking should expect waiting times of 3 to 6 days.',
    url:'https://pancanal.com/advisory/2026-27', publishedAt:'2026-08-30T15:00:00Z', collectedAt:'2026-08-30T15:20:00Z', processStatus:'PROCESSED' },
  { rawFeedId:'RF06', sourceId:'SRC05', externalId:'CN-SG-2026-09',
    title:'Customer Advisory - Berth waiting time at Singapore (PSA) terminals',
    body:'Average berth waiting time at PSA Singapore has risen to 3.2 days as a result of vessel bunching following Red Sea re-routings. Customers should factor an additional 2-4 days into transit planning for services calling Singapore until mid-October.',
    url:'https://carrier.example/advisory/cn-sg-2026-09', publishedAt:'2026-09-05T08:00:00Z', collectedAt:'2026-09-05T08:30:00Z', processStatus:'PROCESSED' },
  { rawFeedId:'RF07', sourceId:'SRC02', externalId:'RTRS-2026-0913-TAR',
    title:'US to impose additional 25% tariff on Chinese and Korean electronic components from Sept 14',
    body:'The US Trade Representative confirmed that an additional 25 percent duty on a list of 114 electronic component HS codes originating in China and South Korea takes effect for goods entered for consumption on or after 14 SEP 2026. Customs brokers at Los Angeles and Long Beach report extended documentary review for affected entries, with average clearance times rising by 3 to 4 days.',
    url:'https://reuters.com/2026/0913/tariff', publishedAt:'2026-09-13T22:10:00Z', collectedAt:'2026-09-13T22:22:00Z', processStatus:'PROCESSED' },
  { rawFeedId:'RF08', sourceId:'SRC07', externalId:'TW-2026-0911-PIR',
    title:'ReCAAP reports uptick in petty theft incidents in Malacca and Singapore Straits',
    body:'ReCAAP ISC recorded nine incidents of boarding for theft in the Straits of Malacca and Singapore during August 2026, up from four in the same month last year. All incidents involved opportunistic theft of ship stores; no crew injuries were reported.',
    url:'https://tradewindsnews.com/2026/0911', publishedAt:'2026-09-11T05:00:00Z', collectedAt:'2026-09-11T05:26:00Z', processStatus:'PROCESSED' },
  { rawFeedId:'RF09', sourceId:'SRC02', externalId:'RTRS-2026-0914-TWN',
    title:'China announces live-fire exercise zone east of Taiwan Strait median line',
    body:'China maritime safety administration issued a navigational warning designating a live-fire exercise area effective 14-20 SEP 2026. Commercial traffic is advised to avoid the designated coordinates. Major carriers have not announced service changes at this time.',
    url:'https://reuters.com/2026/0914/taiwan', publishedAt:'2026-09-14T03:40:00Z', collectedAt:'2026-09-14T03:52:00Z', processStatus:'PROCESSED' },
  { rawFeedId:'RF10', sourceId:'SRC08', externalId:'X-1798234112',
    title:'BREAKING: Suez Canal completely closed, hundreds of ships stuck!!',
    body:'Unverified post claiming total closure of the Suez Canal. No corroborating report from SCA, IMO or UKMTO. Engagement driven account with prior history of maritime misinformation.',
    url:'https://x.com/status/1798234112', publishedAt:'2026-09-13T16:05:00Z', collectedAt:'2026-09-13T16:06:00Z', processStatus:'DISCARDED',
    discardReason:'단일 소셜 출처, 교차 검증 불가 (SCA·IMO·UKMTO 공지 없음). 신뢰도 0.22로 임계값 미달.' },
  { rawFeedId:'RF11', sourceId:'SRC01', externalId:'LL-2026-091502',
    title:'Box rates on Asia-North Europe jump 18% week on week',
    body:'Spot container rates from Asia to North Europe rose 18 percent week on week, the sharpest single week gain since February, as carriers reinstate Cape routings.',
    url:'https://lloydslist.com/2026/091502', publishedAt:'2026-09-15T02:00:00Z', collectedAt:'2026-09-15T02:15:00Z', processStatus:'PENDING' },
  { rawFeedId:'RF12', sourceId:'SRC06', externalId:'NOAA-NA-STORM-03',
    title:'Gale warning - North Atlantic, Bay of Biscay',
    body:'A deepening low will bring sustained winds of 25-30 knots and significant wave heights of 5-6 m across the Bay of Biscay from 17 to 19 SEP 2026.',
    url:'https://noaa.gov/marine/biscay-03', publishedAt:'2026-09-15T03:40:00Z', collectedAt:'2026-09-15T03:47:00Z', processStatus:'PENDING' }
];

export const riskEvents = [
  { eventId:'EV01', rawFeedId:'RF01', eventType:'GEOPOLITICAL', status:'PUBLISHED',
    title:'호르무즈 해협 선박 검문·억류 활동 급증',
    summary:'2026년 9월 8일 이후 호르무즈 해협 일대에서 무장 승선 시도와 선박 억류가 반복 보고되고 있습니다. 컨테이너선 2척이 9월 10일 억류되어 반다르아바스에 계류 중이며, UKMTO는 통과 지연 검토를 권고했습니다.',
    severity:5, confidence:0.88, startDate:'2026-09-08', expectedEndDate:'2026-10-31',
    llmModel:'claude-opus-5', llmExtractedAt:'2026-09-12T06:33:00Z',
    reviewedBy:'U001', reviewedAt:'2026-09-12T07:10:00Z', reviewNote:'UKMTO 원문 및 선사 공지 교차 확인 완료. 발행 승인.',
    publishedAt:'2026-09-12T07:10:00Z' },
  { eventId:'EV02', rawFeedId:'RF02', eventType:'GEOPOLITICAL', status:'PUBLISHED',
    title:'홍해·바브엘만데브 상선 공격 재개',
    summary:'3개월간의 소강 상태 이후 홍해 남부와 바브엘만데브 해협에서 상선 대상 공격이 재개되었습니다. 9월 1~9일 사이 무인수상정(USV) 공격 3건이 보고되었고, 전쟁위험 보험 할증구역이 재지정되었습니다. 선사들은 희망봉 우회 또는 야간 고속 통과를 권고받고 있습니다.',
    severity:5, confidence:0.88, startDate:'2026-09-01', expectedEndDate:'2026-11-30',
    llmModel:'claude-opus-5', llmExtractedAt:'2026-09-01T11:16:00Z',
    reviewedBy:'U001', reviewedAt:'2026-09-01T12:00:00Z', reviewNote:'심각도 4 → 5 상향 (USV 공격은 선체 직접 타격 위험).',
    publishedAt:'2026-09-01T12:00:00Z' },
  { eventId:'EV03', rawFeedId:'RF03', eventType:'WEATHER', status:'PUBLISHED',
    title:"태풍 '너구리(NEGURI)' 북상, 상하이·닝보 항만 운영 중단 예고",
    summary:'태풍 너구리가 9월 17~19일 양쯔강 하구 부근 상륙할 것으로 예보되었습니다. 상하이항만공사는 양산·외고교 터미널에 대해 9월 16일 18시 현지시각 기준 사전 폐쇄를 공지했으며, 닝보-저우산항은 약 48시간 운영 중단이 예상됩니다.',
    severity:3, confidence:0.95, startDate:'2026-09-16', expectedEndDate:'2026-09-22',
    llmModel:'claude-opus-5', llmExtractedAt:'2026-09-14T21:14:00Z',
    reviewedBy:'U001', reviewedAt:'2026-09-14T22:00:00Z', reviewNote:'기상 예보 신뢰도 높음. 자동 발행.',
    publishedAt:'2026-09-14T22:00:00Z' },
  { eventId:'EV04', rawFeedId:'RF04', eventType:'LABOR_STRIKE', status:'PUBLISHED',
    title:'로테르담·안트베르펜 항만 노조 72시간 파업 예고',
    summary:'터미널 자동화 협상 결렬로 FNV Havens와 ABVV Transcom이 10월 14~17일 72시간 공동 파업을 예고했습니다. 1주 순환 파업으로의 확대 가능성도 배제되지 않아 선석 생산성의 급격한 저하가 예상됩니다.',
    severity:3, confidence:0.72, startDate:'2026-10-12', expectedEndDate:'2026-10-22',
    llmModel:'claude-opus-5', llmExtractedAt:'2026-09-14T09:44:00Z',
    reviewedBy:'U001', reviewedAt:'2026-09-14T10:20:00Z', reviewNote:'협상 타결 시 철회 가능성 있어 신뢰도 0.72 유지.',
    publishedAt:'2026-09-14T10:20:00Z' },
  { eventId:'EV05', rawFeedId:'RF05', eventType:'WEATHER', status:'PUBLISHED',
    title:'파나마 운하 가뭄에 따른 일일 통항 슬롯 감축 (32→27)',
    summary:'가툰 호수 유역의 강수량 부족이 지속되면서 파나마운하청이 9월 1일부터 일일 예약 슬롯을 32척에서 27척으로 감축했습니다. 사전 예약이 없는 선박은 3~6일의 대기가 예상됩니다.',
    severity:2, confidence:0.90, startDate:'2026-09-01', expectedEndDate:'2026-12-31',
    llmModel:'claude-opus-5', llmExtractedAt:'2026-08-30T15:22:00Z',
    reviewedBy:'U001', reviewedAt:'2026-08-30T16:00:00Z', reviewNote:'',
    publishedAt:'2026-08-30T16:00:00Z' },
  { eventId:'EV06', rawFeedId:'RF06', eventType:'PORT_CONGESTION', status:'PUBLISHED',
    title:'싱가포르항 체선 심화 (평균 선석 대기 3.2일)',
    summary:'홍해 우회에 따른 선박 집중 도착으로 PSA 싱가포르의 평균 선석 대기시간이 3.2일까지 상승했습니다. 10월 중순까지 싱가포르 기항 서비스에 2~4일의 추가 운송기간을 반영할 것이 권고됩니다.',
    severity:2, confidence:0.78, startDate:'2026-09-05', expectedEndDate:'2026-10-15',
    llmModel:'claude-opus-5', llmExtractedAt:'2026-09-05T08:33:00Z',
    reviewedBy:'U001', reviewedAt:'2026-09-05T09:00:00Z', reviewNote:'',
    publishedAt:'2026-09-05T09:00:00Z' },
  { eventId:'EV07', rawFeedId:'RF07', eventType:'REGULATION', status:'PUBLISHED',
    title:'미국, 중국·한국산 전자부품 추가 관세 25% 발효',
    summary:'미국 무역대표부가 전자부품 114개 HS코드에 대해 9월 14일 반입분부터 25% 추가 관세를 발효했습니다. LA·롱비치 통관에서 대상 건의 서류 심사가 강화되어 평균 통관 소요가 3~4일 증가하고 있습니다.',
    severity:3, confidence:0.93, startDate:'2026-09-14', expectedEndDate:'2026-12-31',
    llmModel:'claude-opus-5', llmExtractedAt:'2026-09-13T22:25:00Z',
    reviewedBy:'U001', reviewedAt:'2026-09-14T00:30:00Z', reviewNote:'관세 발효일 기준으로 영향 시작일 설정.',
    publishedAt:'2026-09-14T00:30:00Z' },
  { eventId:'EV08', rawFeedId:'RF08', eventType:'PIRACY', status:'DRAFT',
    title:'말라카·싱가포르 해협 소규모 승선 절도 증가',
    summary:'ReCAAP ISC가 2026년 8월 말라카·싱가포르 해협에서 9건의 승선 절도를 기록했습니다(전년 동월 4건). 전량 선용품 절도이며 선원 부상은 없습니다.',
    severity:2, confidence:0.61, startDate:'2026-09-10', expectedEndDate:'2026-10-10',
    llmModel:'claude-opus-5', llmExtractedAt:'2026-09-11T05:29:00Z',
    reviewedBy:null, reviewedAt:null, reviewNote:null, publishedAt:null },
  { eventId:'EV09', rawFeedId:'RF09', eventType:'GEOPOLITICAL', status:'DRAFT',
    title:'대만해협 중간선 동측 실사격 훈련구역 설정',
    summary:'중국 해사국이 9월 14~20일 실사격 훈련구역을 지정하는 항행경보를 발령했습니다. 주요 선사의 서비스 변경 발표는 아직 없습니다.',
    severity:4, confidence:0.55, startDate:'2026-09-14', expectedEndDate:'2026-09-20',
    llmModel:'claude-opus-5', llmExtractedAt:'2026-09-14T03:55:00Z',
    reviewedBy:null, reviewedAt:null, reviewNote:null, publishedAt:null },
  { eventId:'EV10', rawFeedId:'RF10', eventType:'ACCIDENT', status:'DISMISSED',
    title:'[미확인] 수에즈 운하 전면 폐쇄 주장',
    summary:'단일 소셜 계정의 미확인 주장입니다. SCA·IMO·UKMTO 어느 곳에서도 대응 공지가 확인되지 않았습니다.',
    severity:5, confidence:0.22, startDate:'2026-09-13', expectedEndDate:'2026-09-20',
    llmModel:'claude-opus-5', llmExtractedAt:'2026-09-13T16:08:00Z',
    reviewedBy:'U001', reviewedAt:'2026-09-13T16:40:00Z',
    reviewNote:'신뢰도 임계값(0.50) 미달 및 교차 출처 부재로 기각. 소셜 소스 수집 비활성화 처리.', publishedAt:null }
];

export const eventAreas = [
  { eventAreaId:'EA01', eventId:'EV01', areaType:'CHOKEPOINT', chokePointId:'CP01', portId:null, impactLevel:5, expectedDelayDays:9, startDate:null, endDate:null },
  { eventAreaId:'EA02', eventId:'EV01', areaType:'PORT', portId:'P014', chokePointId:null, impactLevel:4, expectedDelayDays:7, startDate:null, endDate:null },
  { eventAreaId:'EA03', eventId:'EV01', areaType:'PORT', portId:'P013', chokePointId:null, impactLevel:3, expectedDelayDays:4, startDate:null, endDate:null },
  { eventAreaId:'EA04', eventId:'EV02', areaType:'CHOKEPOINT', chokePointId:'CP02', portId:null, impactLevel:5, expectedDelayDays:12, startDate:null, endDate:null },
  { eventAreaId:'EA05', eventId:'EV02', areaType:'CHOKEPOINT', chokePointId:'CP03', portId:null, impactLevel:4, expectedDelayDays:10, startDate:null, endDate:null },
  { eventAreaId:'EA06', eventId:'EV02', areaType:'CHOKEPOINT', chokePointId:'CP04', portId:null, impactLevel:3, expectedDelayDays:5, startDate:null, endDate:null },
  { eventAreaId:'EA07', eventId:'EV02', areaType:'PORT', portId:'P015', chokePointId:null, impactLevel:3, expectedDelayDays:6, startDate:null, endDate:null },
  { eventAreaId:'EA08', eventId:'EV03', areaType:'PORT', portId:'P003', chokePointId:null, impactLevel:4, expectedDelayDays:5, startDate:null, endDate:null },
  { eventAreaId:'EA09', eventId:'EV03', areaType:'PORT', portId:'P004', chokePointId:null, impactLevel:3, expectedDelayDays:3, startDate:null, endDate:null },
  { eventAreaId:'EA10', eventId:'EV04', areaType:'PORT', portId:'P017', chokePointId:null, impactLevel:4, expectedDelayDays:6, startDate:null, endDate:null },
  { eventAreaId:'EA11', eventId:'EV04', areaType:'PORT', portId:'P019', chokePointId:null, impactLevel:3, expectedDelayDays:4, startDate:null, endDate:null },
  { eventAreaId:'EA12', eventId:'EV05', areaType:'CHOKEPOINT', chokePointId:'CP06', portId:null, impactLevel:3, expectedDelayDays:4, startDate:null, endDate:null },
  { eventAreaId:'EA13', eventId:'EV06', areaType:'PORT', portId:'P010', chokePointId:null, impactLevel:3, expectedDelayDays:3, startDate:null, endDate:null },
  { eventAreaId:'EA14', eventId:'EV07', areaType:'PORT', portId:'P021', chokePointId:null, impactLevel:3, expectedDelayDays:4, startDate:null, endDate:null },
  { eventAreaId:'EA15', eventId:'EV07', areaType:'PORT', portId:'P022', chokePointId:null, impactLevel:3, expectedDelayDays:4, startDate:null, endDate:null },
  { eventAreaId:'EA16', eventId:'EV07', areaType:'PORT', portId:'P023', chokePointId:null, impactLevel:2, expectedDelayDays:2, startDate:null, endDate:null },
  { eventAreaId:'EA17', eventId:'EV08', areaType:'CHOKEPOINT', chokePointId:'CP05', portId:null, impactLevel:2, expectedDelayDays:1, startDate:null, endDate:null },
  { eventAreaId:'EA18', eventId:'EV09', areaType:'CHOKEPOINT', chokePointId:'CP08', portId:null, impactLevel:4, expectedDelayDays:3, startDate:null, endDate:null },
  { eventAreaId:'EA19', eventId:'EV10', areaType:'CHOKEPOINT', chokePointId:'CP04', portId:null, impactLevel:5, expectedDelayDays:20, startDate:null, endDate:null }
];
